### PR TITLE
[SIW-1063] Update NextJS and Redux

### PR DESCRIPTION
**Pull request by gunzip**
## Short description

Update NextJS and Redux.

## List of changes proposed in this pull request

Updated NextJS to 14.x and Redux to 9.x.

## How to test

yarn install
yarn build

### CODE REVIEW

**Comment by gunzip** [comment]
depends on #146

**Comment by gunzip** [comment]
@Ladirico can we merge this one?

**Review by Ladirico — APPROVED** [review]
LGTM

**Comment by gunzip** [comment]
There's an issue between next-intl 2.x and next 14.x. To upgrade to Next 14.x we must update next-intl to 3.x but this requires some changes, ie. https://next-intl-docs.vercel.app/docs/getting-started/app-router#static-rendering 

So, I'm marking this as don't merge by now.

**Pull request closed without merging**
